//! `did:key` device identifiers — `CON-205`, `REQ-206`, `REQ-215`.
//!
//! A device grant names its subject as `did:key:<device>` and carries the same
//! Ed25519 public key again in `cnf.jwk`. `CON-205` closes the gap between them:
//! the credential "MUST make the `cnf.jwk` key equal the Ed25519 key encoded by
//! the device DID."
//!
//! That equality is the whole reason this module exists. Two places name one
//! key, so one of them could name a different key, and a verifier that checked
//! only the JWK would accept a grant whose *subject* was somebody else's device.
//! [`decode`] is what makes the check possible: it recovers the key the DID
//! encodes so the two can be compared as octets rather than as strings.
//!
//! # The encoding
//!
//! ```text
//! did:key:z<base58btc(0xED 0x01 || public_key_32)>
//! ```
//!
//! `z` is the multibase prefix for base58btc, and `0xED 0x01` is the unsigned
//! varint for multicodec `ed25519-pub`. Both are fixed: this profile admits no
//! other curve (`NFR-208`), so there is no algorithm for untrusted input to
//! select — a `did:key` naming a P-256 or secp256k1 key is refused as malformed
//! rather than dispatched to another verifier.
//!
//! # Device keys are per application account
//!
//! `REQ-215` requires a distinct key for each `(applicationId, accountScopeId,
//! device installation)` tuple, generated by the device CSPRNG and never derived
//! from the recovery secret or the home seed. The rationale is worth restating
//! because it is easy to lose: pairwise home DIDs do not provide pairwise privacy
//! if two credentials expose the same device DID. This module encodes and decodes
//! keys; enforcing that they are not reused across scopes belongs to the shell
//! that holds them, and `TEST-221` is its test.

use crate::codec::{self, CodecError};

/// The multibase prefix for base58btc.
const MULTIBASE_BASE58BTC: char = 'z';

/// The multicodec varint for `ed25519-pub`.
const MULTICODEC_ED25519_PUB: [u8; 2] = [0xED, 0x01];

/// Why a `did:key` was refused.
#[derive(Clone, Copy, Debug, PartialEq, Eq, thiserror::Error)]
pub enum DidKeyError {
    /// The identifier does not begin `did:key:z`.
    #[error("not a base58btc did:key")]
    NotDidKey,
    /// The base58 body is not canonical or uses characters outside the alphabet.
    #[error("did:key body is not canonical base58btc")]
    BadEncoding,
    /// The multicodec prefix is not `ed25519-pub`.
    ///
    /// `NFR-208` confines version 1 to Ed25519, so another curve is malformed
    /// input rather than a different algorithm to dispatch on.
    #[error("did:key does not encode an Ed25519 public key")]
    NotEd25519,
    /// The decoded key is not 32 octets.
    #[error("did:key does not carry a 32-octet key")]
    BadKeyLength,
    /// The octets are not a valid Ed25519 point.
    #[error("did:key does not encode a valid Ed25519 public key")]
    NotAValidPoint,
}

/// Encode an Ed25519 public key as a `did:key` identifier.
pub fn encode(public_key: &[u8; 32]) -> String {
    let mut body = Vec::with_capacity(34);
    body.extend_from_slice(&MULTICODEC_ED25519_PUB);
    body.extend_from_slice(public_key);
    format!("did:key:{MULTIBASE_BASE58BTC}{}", codec::base58btc(&body))
}

/// Recover the Ed25519 public key a `did:key` encodes.
pub fn decode(did: &str) -> Result<[u8; 32], DidKeyError> {
    let body = did
        .strip_prefix("did:key:")
        .and_then(|rest| rest.strip_prefix(MULTIBASE_BASE58BTC))
        .ok_or(DidKeyError::NotDidKey)?;
    let octets = codec::decode_base58btc(body).map_err(|e| match e {
        CodecError::BadAlphabet => DidKeyError::BadEncoding,
        _ => DidKeyError::BadEncoding,
    })?;
    if octets.len() < 2 || octets[..2] != MULTICODEC_ED25519_PUB {
        return Err(DidKeyError::NotEd25519);
    }
    if octets.len() != 34 {
        return Err(DidKeyError::BadKeyLength);
    }
    let mut key = [0u8; 32];
    key.copy_from_slice(&octets[2..]);
    // A key that is not a valid point can never verify a signature, so accepting
    // one would mean carrying a device DID whose proof step is unsatisfiable —
    // a grant that looks issuable and is not usable.
    ed25519_dalek::VerifyingKey::from_bytes(&key).map_err(|_| DidKeyError::NotAValidPoint)?;
    Ok(key)
}

/// `CON-205`'s cross-field equality: the `cnf.jwk` key equals the key the device
/// DID encodes.
pub fn matches_jwk(device_did: &str, jwk_public_key: &[u8; 32]) -> Result<(), DidKeyError> {
    let encoded = decode(device_did)?;
    if &encoded == jwk_public_key {
        Ok(())
    } else {
        Err(DidKeyError::NotAValidPoint)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn public_key(seed: u8) -> [u8; 32] {
        ed25519_dalek::SigningKey::from_bytes(&[seed; 32]).verifying_key().to_bytes()
    }

    #[test]
    fn round_trips_a_device_key() {
        let key = public_key(3);
        let did = encode(&key);
        assert!(did.starts_with("did:key:z"), "{did}");
        assert_eq!(decode(&did).unwrap(), key);
    }

    #[test]
    fn matches_the_published_did_key_vector() {
        // The W3C did:key test vector for an all-zero-ish Ed25519 key is not
        // convenient to state, so this pins the two fixed prefixes instead —
        // which is what a second implementation actually has to reproduce.
        let key = [0u8; 32];
        let did = encode(&key);
        let body = did.strip_prefix("did:key:z").unwrap();
        let octets = codec::decode_base58btc(body).unwrap();
        assert_eq!(&octets[..2], &[0xED, 0x01]);
        assert_eq!(&octets[2..], &key);
    }

    #[test]
    fn distinct_keys_give_distinct_identifiers() {
        assert_ne!(encode(&public_key(1)), encode(&public_key(2)));
    }

    #[test]
    fn rejects_a_did_that_is_not_a_base58_did_key() {
        for did in [
            "did:crdt:abc",
            "did:key:abc",
            "did:key:z",
            "key:z6Mk",
            "",
            "did:key:Q3shbg", // multibase `Q`, not `z`
        ] {
            assert!(decode(did).is_err(), "{did} was accepted");
        }
    }

    #[test]
    fn rejects_another_curve() {
        // multicodec `p256-pub` is 0x80 0x24.
        let mut body = vec![0x80, 0x24];
        body.extend_from_slice(&[1u8; 33]);
        let did = format!("did:key:z{}", codec::base58btc(&body));
        assert_eq!(decode(&did), Err(DidKeyError::NotEd25519));
    }

    #[test]
    fn rejects_a_wrong_length_key() {
        let mut body = MULTICODEC_ED25519_PUB.to_vec();
        body.extend_from_slice(&[1u8; 31]);
        let did = format!("did:key:z{}", codec::base58btc(&body));
        assert_eq!(decode(&did), Err(DidKeyError::BadKeyLength));
    }

    #[test]
    fn rejects_octets_that_are_not_a_valid_ed25519_point() {
        // `[0x02; 32]` is a compressed encoding whose y-coordinate has no
        // corresponding curve point. Accepting it would produce a device DID
        // whose proof step is unsatisfiable — a grant that looks issuable and
        // can never be used, which is worse than one refused at issuance.
        let mut body = MULTICODEC_ED25519_PUB.to_vec();
        body.extend_from_slice(&[0x02u8; 32]);
        let did = format!("did:key:z{}", codec::base58btc(&body));
        assert_eq!(decode(&did), Err(DidKeyError::NotAValidPoint));
    }

    // TEST-209: the cross-field equality CON-205 requires.
    #[test]
    fn the_cnf_key_must_equal_the_key_the_subject_did_encodes() {
        let key = public_key(3);
        let did = encode(&key);
        assert!(matches_jwk(&did, &key).is_ok());
        // A grant naming one device and carrying another device's key is the
        // exact substitution this check exists for.
        assert!(matches_jwk(&did, &public_key(4)).is_err());
    }
}
