/**
 * Screen-render check for Selfsame.
 *
 * Walks every screen of the flow with a stubbed Tauri bridge and asserts three
 * things a Rust test cannot see: exactly one screen is visible at a time, no
 * screen overflows horizontally at phone width, and nothing throws on the way
 * through. It also writes a PNG per screen, which is how the implementation is
 * compared against `docs/mockup/Selfsame.html`.
 *
 * The bridge returns the shapes the real commands return. It is deliberately
 * dumb: this file checks *presentation*, and every security decision it might
 * otherwise appear to exercise is made in `selfsame-core` and tested there.
 *
 *   node apps/selfsame/tests/screens.mjs out/
 */
import puppeteer from 'puppeteer';
import { createServer } from 'node:http';
import { readFileSync, mkdirSync } from 'node:fs';
import { extname, join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// ES modules are blocked from file:// origins, so serve the real directory.
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', 'src');
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' };
const server = createServer((req, res) => {
  const path = req.url === '/' ? '/index.html' : req.url.split('?')[0];
  try {
    const body = readFileSync(join(ROOT, path));
    res.writeHead(200, { 'content-type': MIME[extname(path)] || 'application/octet-stream' });
    res.end(body);
  } catch {
    res.writeHead(404).end();
  }
});
await new Promise((r) => server.listen(0, '127.0.0.1', r));
const SRC = `http://127.0.0.1:${server.address().port}/index.html`;
const OUT = process.argv[2] ?? 'screens-out';
mkdirSync(OUT, { recursive: true });

// Fingerprints cross the bridge as all three renderings — `hex` is the value
// the user is ever asked to compare, `label` names a row, `lifehash` is the
// picture. See `commands.rs::Fp` and SPEC-002 CON-102.
//
// The pictures are real: generated by `selfsame-core` from the very digests
// these hexes render, so the screenshots show what the app shows rather than
// noise shaped like it. A synthetic buffer would satisfy the assertions below
// and quietly stop the captures being worth comparing against the mockup.
const LH = JSON.parse(readFileSync(join(dirname(fileURLToPath(import.meta.url)), 'lifehash-fixtures.json'), 'utf8'));
// ROOT_FP and DID_FP are DIFFERENT VALUES, and that is the point of the stub.
//
// `get_state` returns both: `root_fingerprint` is `fingerprint_key(root_pk)`
// and `fingerprint` is `fingerprint_did(did)`. They are separate domains over
// separate inputs, so they never agree. An earlier version of this file used
// one constant for both, which made the app look self-consistent in every
// screenshot when it is not: the *created* screen shows the DID fingerprint and
// the *home* card shows the root-key one.
const ROOT_FP = { hex: '5F 9A C9 07 2E 11', label: 'slate-heron-07', lifehash: LH['root_5F9AC9072E11'] };
const DID_FP = { hex: '2E 41 D0 88 6B 15', label: 'garnet-plover-31', lifehash: LH['did_2E41D0886B15'] };
const KEY_FP = { hex: 'C0 7A 1E 42 9B 33', label: 'copper-lynx-42', lifehash: LH['key_C07A1E429B33'] };

// ── IMPL-004 · the SPEC-004 surface ──────────────────────────────────────
//
// HOME_FP is a real fingerprint of the stub home DID CON-603 returns, with a
// real LifeHash of that digest — same discipline as the constants above. The
// DID's *provenance* is fixture (see FINDING-016: the wallet holds no material
// to derive one), but everything rendered from it is genuinely computed.
const HOME_DID = 'did:crdt:4b8e2f7a91c05d63e8f240ab17c9d3e56082f4a1bc7d90e35f61a284c093db7e';
// A DIFFERENT identity, and that is the point of the fixture. CON-202 gives each
// application its own home below the recovery secret, and the applications
// screen says so in as many words. Sharing one DID across both rows would make
// a real cross-application linkability defect look correct on screen.
const HOME_DID_2 = 'did:crdt:c17d0e93b426a8f5104e7b2c96d38af0521e6bc94d70382af659c1e04b7d28a3';
const HOME_FP = { hex: 'FF 9E 3B 49 7A 49', label: 'cobalt-quarry-27', lifehash: LH['home_FF9E3B497A49'] };

// The account alias is the opaque one CON-203 derives from the home DID. The
// account *scope* appears nowhere here and must appear nowhere on screen
// (NFR-203) — the fixture cannot leak what it does not carry.
const APPLICATIONS = [
  {
    application_id: 'https://photos.example/selfsame/application',
    display_name: 'Photos',
    account_alias: 'acct:ss-k4f7q2m9x3v6b8n1p5r0t2w4y6z8a1c3e5g7@accounts.photos.example',
    username: 'alice',
    home_did: HOME_DID,
    fingerprint: HOME_FP,
    permissions: [
      { uri: 'https://photos.example/selfsame/application#device', title: 'Act as this account on this device', known: true },
      { uri: 'https://photos.example/selfsame/application#upload', title: null, known: false },
    ],
    devices: [
      { label: 'This phone', grant_id: `${HOME_DID}#grant-AAAA`, added_at: Math.floor(Date.now()/1000) - 86400, is_this_device: true },
      { label: 'Laptop', grant_id: `${HOME_DID}#grant-BBBB`, added_at: Math.floor(Date.now()/1000) - 604800, is_this_device: false },
    ],
  },
  {
    application_id: 'https://notes.example/selfsame/application',
    display_name: 'Notes',
    // HP-7's cliff: the application has not supplied this account's scope, so
    // there is no alias and no identity to open. REQ-217 forbids guessing one.
    account_alias: null,
    username: null,
    home_did: HOME_DID_2,
    fingerprint: HOME_FP,
    permissions: [],
    devices: [],
  },
];

const STATE_APPS = {
  has_identity: true,
  backup_confirmed: true,
  did: 'did:crdt:9f3a11c2e70b4d8a5c6f9012ab34cd56ef78901234abcd56ef7890123456abcd',
  fingerprint: { hex: '2E 41 D0 88 6B 15', label: 'garnet-plover-31', lifehash: LH['did_2E41D0886B15'] },
  root_fingerprint: { hex: '5F 9A C9 07 2E 11', label: 'slate-heron-07', lifehash: LH['root_5F9AC9072E11'] },
  pending_publications: 0,
  devices: [],
  applications: APPLICATIONS,
};

// CON-210: only a re-resolved verified closure moves a removal to confirmed.
// Two states rather than a timer or a button — the screen asks, and the answer
// decides. `28-remove-pending` asks and is told no; `29` asks and is told yes.
const STATE_APPS_SETTLED = { ...STATE_APPS, revocation_settled: true };

// CON-222: the wallet is opened by a caller whose attribution does not match
// the CON-214 binding. An arrival state, so it needs no click path.
const STATE_BAD_CALLER = {
  ...STATE_APPS,
  pending_handoff: {
    caller_matches: false,
    claimed: 'android:com.example.photos',
    observed: 'com.attacker.lookalike',
  },
};

const STATE_LINKED = {
  has_identity: true,
  backup_confirmed: true,
  did: 'did:crdt:9f3a11c2e70b4d8a5c6f9012ab34cd56ef78901234abcd56ef7890123456abcd',
  fingerprint: DID_FP,
  root_fingerprint: ROOT_FP,
  pending_publications: 1,
  devices: [
    { method_id: 'did:crdt:9f3a…#dev-1', label: 'Chrome on macOS', nickname: 'copper-lynx-42', lifehash: LH['dev1_C07A1E429B33'], revoked: false, last_seen: Math.floor(Date.now()/1000) - 120, pending: false },
    { method_id: 'did:crdt:9f3a…#dev-2', label: 'hark on workstation-01', nickname: 'amber-quoll-88', lifehash: LH['dev2_1B44E7902A05'], revoked: false, last_seen: null, pending: true },
    { method_id: 'did:crdt:9f3a…#dev-3', label: 'Firefox on the old laptop', nickname: 'walnut-stoat-19', lifehash: LH['dev3_77C10D3E5182'], revoked: true, last_seen: null, pending: false },
  ],
};

const bridge = (state) => `
  window.__TAURI__ = {
    core: {
      invoke: async (cmd, args) => {
        switch (cmd) {
          case 'get_state': return ${JSON.stringify(state)};
          case 'service_endpoint': return 'http://127.0.0.1:8787';
          case 'create_identity': return {
            words: ['harbour','lichen','quarry','saddle','verbena','tundra','gravel','mussel','plover','basalt','ferment','willow'],
            did: ${JSON.stringify(STATE_LINKED.did)},
            fingerprint: ${JSON.stringify(DID_FP)},
          };
          case 'confirm_backup': return true;
          case 'restore_identity': return null;
          // The refusal path. The shell must render a refusal without learning
          // which check failed, so the stub throws the same opaque line the
          // real command produces.
          case 'read_link_code': if (args.code.endsWith('z')) throw "That code isn't valid.";
          return {
            application: 'cbcl-chat',
            purpose: 'chat-device',
            device_description: 'Chrome on macOS',
            key_fingerprint: ${JSON.stringify(KEY_FP)},
            expires_in: 252,
          };
          case 'authorise': return {
            method_id: 'did:crdt:9f3a…#dev-1',
            did: ${JSON.stringify(STATE_LINKED.did)},
            fingerprint: ${JSON.stringify(DID_FP)},
            publishing: 1,
          };
          case 'unlink_device': return null;
          case 'reject_offer': return null;
          case 'flush_publications': return 0;

          // ── IMPL-004 CON-601..603 ──────────────────────────────────────
          case 'alias_preview': {
            // The refusal path: CON-601 returns one closed token and no detail.
            if (args.localpart === 'admin') throw 'UsernameUnavailable';
            return {
              stableAlias: ${JSON.stringify(APPLICATIONS[0].account_alias)},
              usernameAlias: args.localpart
                ? 'acct:' + args.localpart + '@accounts.photos.example'
                : null,
            };
          }
          case 'home_fingerprint': return ${JSON.stringify(HOME_FP)};
          // CON-204. There is no account authority in this build, so a name can
          // be recognised and never reserved — and the wallet says so rather
          // than showing it as held.
          case 'provision_username': throw 'AccountProvisioningFailed';
          case 'app_identity_derive': {
            if (!args.accountScopeId) throw 'AccountScopeUnavailable';
            return { homeDid: ${JSON.stringify(HOME_DID)}, publicKey: 'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE' };
          }
          case 'revoke_grant': return null;
          case 'revocation_status': return { confirmed: ${JSON.stringify(state)}.revocation_settled === true };

          default: return null;
        }
      },
    },
  };
`;

const shots = [
  { name: '01-welcome', state: { has_identity: false, backup_confirmed: false, devices: [], pending_publications: 0 }, steps: [] },
  { name: '02-passcode', state: { has_identity: false, backup_confirmed: false, devices: [], pending_publications: 0 }, steps: ['begin-create'] },
  { name: '03-phrase', state: { has_identity: false, backup_confirmed: false, devices: [], pending_publications: 0 }, steps: ['begin-create', 'fill-passcode', 'create-identity'] },
  { name: '04-confirm', state: { has_identity: false, backup_confirmed: false, devices: [], pending_publications: 0 }, steps: ['begin-create', 'fill-passcode', 'create-identity', 'to-confirm'] },
  { name: '05-created', state: { has_identity: false, backup_confirmed: false, devices: [], pending_publications: 0 }, steps: ['begin-create', 'fill-passcode', 'create-identity', 'to-confirm', 'check-backup'] },
  { name: '06-home', state: STATE_LINKED, steps: [] },
  { name: '07-type-code', state: STATE_LINKED, steps: ['to-link'] },
  { name: '08-consent', state: STATE_LINKED, steps: ['to-link', 'fill-code', 'read-code'] },
  { name: '09-presence', state: STATE_LINKED, steps: ['to-link', 'fill-code', 'read-code', 'to-presence'] },
  { name: '10-linked', state: STATE_LINKED, steps: ['to-link', 'fill-code', 'read-code', 'to-presence', 'authorise'] },
  { name: '11-rejected', state: STATE_LINKED, steps: ['to-link', 'fill-code', 'read-code', 'reject'] },
  { name: '12-device', state: STATE_LINKED, steps: ['open-device'] },
  { name: '13-unlink', state: STATE_LINKED, steps: ['open-device', 'to-unlink'] },
  { name: '14-restore', state: { has_identity: false, backup_confirmed: false, devices: [], pending_publications: 0 }, steps: ['begin-restore'] },
  { name: '15-restored', state: STATE_LINKED, steps: ['begin-restore', 'fill-restore', 'restore'] },
  { name: '16-unlinked', state: STATE_LINKED, steps: ['open-device', 'to-unlink', 'fill-unlink-passcode', 'unlink'] },
  { name: '17-refused-code', state: STATE_LINKED, steps: ['to-link', 'fill-bad-code', 'read-code'] },

  // ── IMPL-004 · TEST-601..613 ─────────────────────────────────────────
  { name: '18-applications', expect: 'applications', state: STATE_APPS, steps: ['to-applications'] },
  { name: '19-application', expect: 'application', state: STATE_APPS, steps: ['to-applications', 'open-application'] },
  { name: '20-username-set', expect: 'username-set', state: STATE_APPS, steps: ['to-applications', 'open-application', 'to-username'] },
  { name: '21-username-unprovisioned', expect: 'username-set', state: STATE_APPS, steps: ['to-applications', 'open-application', 'to-username', 'fill-username', 'set-username'] },
  { name: '21b-username-taken', expect: 'username-taken', state: STATE_APPS, steps: ['to-applications', 'open-application', 'to-username', 'fill-taken-username', 'set-username'] },
  { name: '22-fingerprint-compare', expect: 'fingerprint-compare', state: STATE_APPS, steps: ['to-applications', 'open-application', 'to-fingerprint'] },
  { name: '23-consent-application', expect: 'consent-application', state: STATE_APPS, steps: ['to-applications', 'open-application', 'to-app-consent'] },
  { name: '24-binding-mismatch', expect: 'binding-mismatch', state: STATE_BAD_CALLER, steps: [] },
  { name: '25-remove-device', expect: 'remove-device', state: STATE_APPS, steps: ['to-applications', 'open-application', 'open-grant', 'to-remove-device'] },
  { name: '26-remove-pending', expect: 'remove-pending', state: STATE_APPS, steps: ['to-applications', 'open-application', 'open-grant', 'to-remove-device', 'remove-device'] },
  { name: '27-remove-confirmed', expect: 'remove-confirmed', state: STATE_APPS_SETTLED, steps: ['to-applications', 'open-application', 'open-grant', 'to-remove-device', 'remove-device'] },
  { name: '28-scope-unavailable', expect: 'scope-unavailable', state: STATE_APPS, steps: ['to-applications', 'open-unscoped-application'] },
];

// ── Negative-output assertions (IMPL-004 TEST-605 / 611 / 613) ───────────
//
// The half most easily lost. A suite that only checks a screen renders will
// pass a screen that renders *and also* offers a skip, so these assert the
// ABSENCE of an affordance and name the requirement each absence serves.
//
// `forbidden` is a list of [selector, why] pairs evaluated against the visible
// screen. `requiredText` is a substring that must appear.
const SCREEN_RULES = {
  '18-applications': {
    // NFR-203: the account scope never reaches a screen.
    forbidden: [['[data-account-scope]', 'NFR-203 forbids rendering an accountScopeId']],
    // The screen says each application gets its own identity below the recovery
    // words. That is CON-202, and it is the property SPEC-004 exists to deliver,
    // so the fixture behind it has to actually hold.
    distinctHomeDids: true,
  },
  '21-username-unprovisioned': {
    // A name recognised and not reserved is not a name you hold. The screen
    // must say so rather than returning as though it were claimed.
    requiredText: 'AccountProvisioningFailed',
  },
  '19-application': {
    forbidden: [['[data-grant-id]', 'a grant ID is held to act on, not rendered']],
  },
  '20-username-set': {
    // NFR-201: the correlation warning is the only control over a voluntarily
    // reused public name, so it is not optional.
    requiredText: 'publicly discoverable',
  },
  '22-fingerprint-compare': {
    // REQ-230 forbids offering a skip. Not "hides" — the control must not exist.
    forbidden: [
      ['[data-action="skip-fingerprint"]', 'REQ-230 forbids offering a skip'],
      ['[data-action="to-home"]', 'REQ-230: a bare exit is a skip wearing another label'],
    ],
  },
  '23-consent-application': {
    // REQ-222: the application's own name may never carry the decision.
    requiredText: 'its own words, unchecked',
  },
    '26-remove-pending': {
    // CON-210 forbids reporting success before a verified closure.
    forbidden: [
      ['[data-action="remove-done"]', 'CON-210 forbids a success affordance while pending'],
      ['.steps__ok', 'CON-210: a completion tick is a success claim'],
    ],
    // A claim is a claim whether it is a control or a sentence. This screen
    // once said "this will keep trying until one does" and "it is retained and
    // retried" — both obligations CON-210 places on a *wired* implementation,
    // neither of them true of this build, which submits once and checks once.
    //
    // Copy drifts back more easily than controls do, because it reads as
    // reassurance rather than as an assertion. So the words are asserted too,
    // and the day retry is implemented this list is what has to be edited
    // deliberately rather than forgotten.
    forbiddenText: [
      ['keep trying', 'nothing retries in this build'],
      ['retried', 'nothing retries in this build'],
      ['retained', 'nothing retains the delta in this build'],
      ['will be removed', 'CON-210 forbids asserting the outcome while pending'],
    ],
    requiredText: 'because nothing has',
  },
  '28-scope-unavailable': {
    // REQ-217 forbids guessing and forbids prompting, so no *remedial* control
    // may exist: no field, no retry, nothing that implies the scope can be
    // supplied from here. `.btn` is this app's action class and is forbidden;
    // `.back` is navigation and is required, because a screen with no exit is a
    // defect rather than compliance — the requirement is about not offering a
    // remedy that does not exist, not about trapping the person who found it.
    forbidden: [
      ['.btn', 'REQ-217 forbids offering a remedial action here'],
      ['input', 'REQ-217 forbids prompting for a scope'],
    ],
    requiredText: 'Sign into the application first',
  },
};

// `protocolTimeout` is raised because a screenshot on a loaded machine can take
// longer than the 30 s default, and a flaky presentation check is worse than a
// slow one.
// CI container runners execute as root, and Chrome's setuid sandbox refuses to
// start as root — the browser dies before the first page loads, which looks
// identical to a broken build. `--no-sandbox` is the standard answer and is
// scoped to CI so a developer's local run keeps the sandbox. `/dev/shm` is
// commonly 64 MB in a container, which Chrome exhausts on the first screenshot.
const CI = !!process.env.CI;
const browser = await puppeteer.launch({
  headless: 'new',
  protocolTimeout: 120_000,
  args: CI ? ['--no-sandbox', '--disable-dev-shm-usage'] : [],
});
const errors = [];

for (const shot of shots) {
  const page = await browser.newPage();
  page.on('pageerror', (e) => errors.push(`${shot.name}: ${e.message}`));
  page.on('console', (m) => { if (m.type() === 'error' && !/favicon|Failed to load resource/.test(m.text())) errors.push(`${shot.name}: console ${m.text()}`); });
  await page.setViewport({ width: 430, height: 900, deviceScaleFactor: 2 });
  // Reduced motion makes the capture deterministic — the scanner sweep and the
  // spinner are infinite animations, and it also exercises the
  // `prefers-reduced-motion` rules in styles.css rather than leaving them
  // unvisited.
  await page.emulateMediaFeatures([{ name: 'prefers-reduced-motion', value: 'reduce' }]);
  await page.evaluateOnNewDocument(bridge(shot.state));
  await page.goto(SRC, { waitUntil: 'networkidle0' });
  await new Promise((r) => setTimeout(r, 250));

  for (const step of shot.steps) {
    if (step === 'fill-passcode') {
      await page.evaluate(() => {
        document.querySelector('#passcode-1').value = 'correct horse';
        document.querySelector('#passcode-2').value = 'correct horse';
      });
    } else if (step === 'fill-code') {
      await page.evaluate(() => {
        const el = document.querySelector('#code-input');
        el.value = 'anuna1qyqsqqqqqqqqqqqqqqqqqqqqqqqqqjdgkrf';
        el.dispatchEvent(new Event('input'));
      });
    } else if (step === 'fill-bad-code') {
      await page.evaluate(() => {
        const el = document.querySelector('#code-input');
        el.value = 'anuna1qyqsqqqqqqqqqqqqqqqqqqqqqqqqqjdgkrz';
        el.dispatchEvent(new Event('input'));
      });
    } else if (step === 'fill-restore') {
      await page.evaluate(() => {
        document.querySelector('#restore-phrase').value =
          'harbour lichen quarry saddle verbena tundra gravel mussel plover basalt ferment willow';
        document.querySelector('#restore-passcode').value = 'correct horse';
      });
    } else if (step === 'fill-unlink-passcode') {
      await page.evaluate(() => {
        document.querySelector('#unlink-passcode').value = 'correct horse';
      });
    } else if (step === 'open-device') {
      await page.evaluate(() => document.querySelector('.device')?.click());
    } else if (step === 'open-application') {
      await page.evaluate(() => document.querySelector('.application')?.click());
    } else if (step === 'open-unscoped-application') {
      // The second fixture application has no scope available — HP-7's cliff.
      await page.evaluate(() => document.querySelectorAll('.application')[1]?.click());
    } else if (step === 'open-grant') {
      await page.evaluate(() => document.querySelector('.grant')?.click());
    } else if (step === 'fill-username') {
      await page.evaluate(() => {
        const el = document.querySelector('#username-input');
        if (el) { el.value = 'alice'; el.dispatchEvent(new Event('input')); }
      });
    } else if (step === 'fill-taken-username') {
      await page.evaluate(() => {
        const el = document.querySelector('#username-input');
        if (el) { el.value = 'admin'; el.dispatchEvent(new Event('input')); }
      });
    } else {
      await page.evaluate((a) => document.querySelector(`[data-action="${a}"]`)?.click(), step);
    }
    await new Promise((r) => setTimeout(r, 250));
  }

  const visible = await page.evaluate(() =>
    [...document.querySelectorAll('.screen')].filter((s) => !s.hidden).map((s) => s.dataset.screen),
  );
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);

  // SPEC-002 TEST-101 / TEST-105 — the visual fingerprint.
  //
  // Read the pixels back rather than trusting the element's presence: a canvas
  // that was never painted is a blank rectangle that looks fine in a
  // screenshot and satisfies any selector you point at it. "More than one
  // distinct colour" is the cheap way to say the LifeHash actually landed.
  const pictures = await page.evaluate(() => {
    const onVisibleScreen = (el) => el.closest('.screen') && !el.closest('.screen').hidden;
    return [...document.querySelectorAll('canvas.fp__lifehash')].filter(onVisibleScreen).map((c) => {
      const out = { hidden: c.hidden, aria: c.getAttribute('aria-hidden'), colours: 0, w: c.width, h: c.height };
      if (!c.hidden && c.width > 0) {
        const data = c.getContext('2d').getImageData(0, 0, c.width, c.height).data;
        const seen = new Set();
        for (let i = 0; i < data.length; i += 4) seen.add((data[i] << 16) | (data[i + 1] << 8) | data[i + 2]);
        out.colours = seen.size;
      }
      // The text REQ-105 requires beside every picture.
      const block = c.closest('.fp, .card, .screen, .device, li');
      out.hasText = !!block && /[0-9A-F]{2} [0-9A-F]{2}|[a-z]+-[a-z]+-\d\d/.test(block.innerText || '');
      return out;
    });
  });

  for (const [i, p] of pictures.entries()) {
    if (p.hidden) { errors.push(`${shot.name}: lifehash ${i} is hidden — it failed CON-102's grammar`); continue; }
    if (p.w !== 32 || p.h !== 32) errors.push(`${shot.name}: lifehash ${i} is ${p.w}×${p.h}, expected 32×32 (CON-101)`);
    if (p.colours < 8) errors.push(`${shot.name}: lifehash ${i} painted only ${p.colours} colours — blank or unpainted (TEST-101)`);
    if (p.aria !== 'true') errors.push(`${shot.name}: lifehash ${i} is not aria-hidden (TEST-105)`);
    if (!p.hasText) errors.push(`${shot.name}: lifehash ${i} has no hex or label beside it (REQ-105)`);
  }
  // REQ-101's table: these screens display a key, so each must show its
  // picture. Home is the root key plus all three devices; restored is the root
  // key plus the two that survived — `renderRestored` drops revoked rows,
  // since a recovered phone is showing you what you still have.
  const MUST_PAINT = {
    '05-created': 1, '06-home': 4, '08-consent': 1, '10-linked': 1,
    // The unlink *confirmation* is deliberately absent from this table: it
    // renders no fingerprint at all, only the device's label, so REQ-101 does
    // not reach it. Whether it should is an open question in SPEC-002.
    '12-device': 1, '15-restored': 3,
  };
  if (MUST_PAINT[shot.name] !== undefined && pictures.length !== MUST_PAINT[shot.name]) {
    errors.push(`${shot.name}: REQ-101 expects ${MUST_PAINT[shot.name]} lifehash canvases, found ${pictures.length}`);
  }

  // Every screen that headlines *the identity* must headline the SAME value the
  // user memorised at creation — the DID fingerprint, which is what every
  // linked client and the CLI compute (`accept.rs`, `fingerprint_did`). The
  // home card used to show `root_fingerprint` instead: a 48-bit value displayed
  // nowhere else in the system, on the screen the user checks to ask "is this
  // still me?".
  const EXPECT_HEX = {
    '05-created': DID_FP.hex, '06-home': DID_FP.hex,
    '10-linked': DID_FP.hex, '15-restored': DID_FP.hex,
  };
  if (EXPECT_HEX[shot.name]) {
    const shown = await page.evaluate(() =>
      document.querySelector('.screen:not([hidden])')?.innerText ?? '');
    if (!shown.includes(EXPECT_HEX[shot.name])) {
      const other = shown.match(/[0-9A-F]{2}(?: [0-9A-F]{2}){5}/)?.[0] ?? 'none';
      errors.push(
        `${shot.name}: headlines ${other}, expected the identity fingerprint ${EXPECT_HEX[shot.name]}`);
    }
  }

  // IMPL-004 negative-output and required-text assertions.
  const rules = SCREEN_RULES[shot.name];
  if (rules) {
    for (const [selector, why] of rules.forbidden ?? []) {
      const present = await page.evaluate((sel) => {
        const screen = document.querySelector('.screen:not([hidden])');
        return !!screen && !!screen.querySelector(sel);
      }, selector);
      if (present) errors.push(`${shot.name}: \`${selector}\` is present — ${why}`);
    }
    const shown = await page.evaluate(() =>
      document.querySelector('.screen:not([hidden])')?.innerText ?? '');
    if (rules.requiredText && !shown.includes(rules.requiredText)) {
      errors.push(`${shot.name}: missing required text "${rules.requiredText}"`);
    }
    for (const [phrase, why] of rules.forbiddenText ?? []) {
      if (shown.toLowerCase().includes(phrase.toLowerCase())) {
        errors.push(`${shot.name}: says "${phrase}" — ${why}`);
      }
    }
    // A claim can also be contradicted by the data behind it rather than by
    // the copy. The applications screen says each application gets its own
    // identity below the recovery words (CON-202) — so the state it renders
    // has to actually give them different ones, or the screen is telling the
    // truth about a system the fixture is not modelling.
    if (rules.distinctHomeDids) {
      const dids = (shot.state.applications ?? []).map((a) => a.home_did);
      if (new Set(dids).size !== dids.length) {
        errors.push(
          `${shot.name}: the fixture shares one home DID across ${dids.length} applications, ` +
          `while the screen claims each gets its own (CON-202)`);
      }
    }
  }

  const pics = pictures.length ? `  lifehash×${pictures.length}` : '';
  console.log(`${shot.name.padEnd(14)} screen=${visible.join(',') || 'NONE'}${pics}${overflow ? '  ⚠ horizontal overflow' : ''}`);
  if (visible.length !== 1) errors.push(`${shot.name}: ${visible.length} screens visible (${visible})`);
  if (overflow) errors.push(`${shot.name}: horizontal overflow at 430px`);
  // "Exactly one screen visible" passes for ANY single screen, so a shot whose
  // navigation silently does nothing still looks green while capturing `home`.
  // `expect` names the screen the steps must actually reach.
  if (shot.expect && visible[0] !== shot.expect) {
    errors.push(`${shot.name}: reached ${visible[0] ?? 'NONE'}, expected ${shot.expect}`);
  }

  try {
    await page.screenshot({ path: `${OUT}/${shot.name}.png` });
  } catch (e) {
    // A failed capture is a reporting problem, not a defect in the page. The
    // structural assertions above have already run.
    console.log(`${' '.repeat(15)}(screenshot skipped: ${e.message.split('\n')[0]})`);
  }
  await page.close();
}

// ── BUG: "Back" from the typed-code screen is a no-op on desktop ─────────
//
// `startLink()` branches on whether the barcode-scanner plugin exists. On
// mobile it shows the scanner; on desktop there is no camera, so it forwards
// straight to the typed-code screen. But that screen's Back button is wired to
// `to-link`, which calls `startLink()` again — and lands back on `type`.
//
// The user is trapped: the only control that looks like an exit re-enters the
// same screen. Every automated check passed because none of them ever pressed
// Back. `12-device` proves the router works; nothing proved it lets go.
{
  const page = await browser.newPage();
  await page.setViewport({ width: 430, height: 900 });
  await page.evaluateOnNewDocument(bridge(STATE_LINKED));
  await page.goto(SRC, { waitUntil: 'networkidle0' });
  await new Promise((r) => setTimeout(r, 250));

  const screenNow = () => page.evaluate(() =>
    document.querySelector('.screen:not([hidden])')?.dataset.screen);

  await page.evaluate(() => document.querySelector('[data-action="to-link"]').click());
  await new Promise((r) => setTimeout(r, 250));
  const arrived = await screenNow();

  // Desktop has no barcodeScanner in the stub, so this is the typed route.
  if (arrived !== 'type') {
    errors.push(`back-from-type: expected the typed-code screen on desktop, got ${arrived}`);
  } else {
    await page.evaluate(() => document.querySelector('[data-screen="type"] .back').click());
    await new Promise((r) => setTimeout(r, 250));
    const after = await screenNow();
    if (after === 'type') {
      errors.push('back-from-type: Back re-entered the typed-code screen — the user cannot leave');
    } else if (after !== 'home') {
      errors.push(`back-from-type: Back should return to home on desktop, got ${after}`);
    } else {
      console.log('back-from-type Back returns to home on desktop');
    }
  }
  await page.close();
}

// ── SPEC-002 TEST-108: the front end recognises before it paints ─────────
//
// CON-102 makes `app.js` a recogniser for the `lifehash` field: a value that
// is not exactly 4096 unpadded Base64 characters decoding to 3072 bytes is
// rejected *whole*, and the screen falls back to the text it always carries
// (REQ-105). The failure mode being ruled out is a half-painted canvas, which
// looks like a real picture and is not one.
{
  const CASES = [
    ['truncated', KEY_FP.lifehash.slice(0, 4000)],
    ['over-long', KEY_FP.lifehash + 'AAAA'],
    ['padded (3072 % 3 == 0, so padding is malformed)', KEY_FP.lifehash.slice(0, 4092) + 'AA=='],
    ['non-base64', 'x'.repeat(4095) + '!'],
    ['not a string', 12345],
    ['absent', undefined],
  ];

  for (const [name, value] of CASES) {
    const page = await browser.newPage();
    const thrown = [];
    page.on('pageerror', (e) => thrown.push(e.message));
    await page.setViewport({ width: 430, height: 900 });
    await page.evaluateOnNewDocument(bridge({
      ...STATE_LINKED,
      // The home card paints `fingerprint` (the identity one) — poison that.
      fingerprint: { ...DID_FP, lifehash: value },
      devices: [],
    }));
    await page.goto(SRC, { waitUntil: 'networkidle0' });
    await new Promise((r) => setTimeout(r, 250));

    const result = await page.evaluate(() => {
      const c = document.querySelector('canvas[data-home-lifehash]');
      return {
        hidden: c?.hidden,
        hex: document.querySelector('[data-home-fingerprint]')?.textContent ?? '',
        screen: document.querySelector('.screen:not([hidden])')?.dataset.screen,
      };
    });

    if (thrown.length) errors.push(`lifehash/${name}: threw instead of rejecting — ${thrown[0]}`);
    if (result.hidden !== true) errors.push(`lifehash/${name}: a malformed value was painted (CON-102)`);
    if (result.screen !== 'home') errors.push(`lifehash/${name}: the screen did not render (got ${result.screen})`);
    if (!/[0-9A-F]{2} /.test(result.hex)) errors.push(`lifehash/${name}: the hex vanished with the picture (REQ-105)`);
    await page.close();
  }
  console.log('lifehash-input malformed values rejected before painting; text survives');
}

// ── SPEC-002 TEST-107: the picture is painted inside the Doherty budget ──
//
// NFR-104 is 400 ms at p95 from the authorise screen becoming visible. The
// budget is generous by construction — the image is computed in Rust before the
// screen is shown and painted from a 3072-byte buffer — so this measures that
// no Game of Life ever ends up on the UI thread by accident.
{
  const page = await browser.newPage();
  await page.setViewport({ width: 430, height: 900 });
  await page.evaluateOnNewDocument(bridge(STATE_LINKED));
  await page.goto(SRC, { waitUntil: 'networkidle0' });
  await new Promise((r) => setTimeout(r, 250));

  const ms = await page.evaluate(async () => {
    document.querySelector('[data-action="to-link"]').click();
    await new Promise((r) => setTimeout(r, 100));
    const el = document.querySelector('#code-input');
    el.value = 'anuna1qyqsqqqqqqqqqqqqqqqqqqqqqqqqqjdgkrf';
    el.dispatchEvent(new Event('input'));

    const started = performance.now();
    document.querySelector('[data-action="read-code"]').click();
    // Resolve on the frame after the consent screen is up and its canvas drawn.
    for (let i = 0; i < 120; i++) {
      await new Promise(requestAnimationFrame);
      const c = document.querySelector('canvas[data-offer-lifehash]');
      const up = !document.querySelector('[data-screen="consent"]').hidden;
      if (up && c && !c.hidden && c.width === 32) {
        const d = c.getContext('2d').getImageData(0, 0, 32, 32).data;
        if (d.some((v, i) => i % 4 !== 3 && v !== 0)) return performance.now() - started;
      }
    }
    return Infinity;
  });

  if (!(ms < 400)) errors.push(`lifehash-latency: authorise screen painted in ${ms}ms, NFR-104 budget is 400ms`);
  else console.log(`lifehash-latency authorise screen painted in ${Math.round(ms)}ms (NFR-104 budget 400ms)`);
  await page.close();
}

// ── the bridge itself ────────────────────────────────────────────────────
//
// Every case above injects a stub, so none of them can see the bridge being
// *absent* — which is exactly the bug that shipped: Tauri v2 does not expose
// `window.__TAURI__` unless `app.withGlobalTauri` is set, `app.js` threw on its
// first line, and the window rendered as a black rectangle with no explanation.
// This case loads the page with **no stub at all** and asserts the failure is
// legible.
{
  const page = await browser.newPage();
  await page.setViewport({ width: 430, height: 900 });
  await page.goto(SRC, { waitUntil: 'networkidle0' });
  await new Promise((r) => setTimeout(r, 250));
  const text = await page.evaluate(() => document.body.innerText);
  if (!/can't reach its own backend/i.test(text)) {
    errors.push(`no-bridge: a missing window.__TAURI__ must render an explanation, got: ${JSON.stringify(text.slice(0, 120))}`);
  } else {
    console.log('no-bridge      renders an explanation rather than a black screen');
  }
  await page.close();
}

await browser.close();
server.close();
if (errors.length) {
  console.log('\nERRORS:');
  for (const e of errors) console.log('  ' + e);
  process.exit(1);
}
console.log('\nall screens rendered clean');
