//! The Rust↔Kotlin contract of SPEC-004 CON-301, checked without a device.
//!
//! TEST-301 through TEST-303 need an Android runtime and cannot run here. What
//! *can* run here is the part of CON-301 that is a contract between two
//! languages, and it is worth running because it is the part that breaks
//! silently: rename a command or a state on one side and the other side stops
//! understanding it, with nothing failing until someone installs an APK and taps
//! a button. That is exactly the loop BUG-201 came out of.
//!
//! Both files are read at compile time, so these tests cannot go stale against a
//! moved file — they stop compiling instead.

use tauri_plugin_selfsame_store::{LoadResponse, StoreError};

const RUST: &str = include_str!("../src/lib.rs");
const KOTLIN: &str = include_str!("../android/src/main/java/SecureStorePlugin.kt");

/// Every command name Rust asks the Kotlin side for.
///
/// Matched on `run_mobile_plugin::<`, which is the call and never prose — the
/// module documentation names the function too, and a looser pattern would count
/// the prose.
fn rust_command_names() -> Vec<&'static str> {
    RUST.match_indices("run_mobile_plugin::<")
        .map(|(at, _)| {
            let rest = &RUST[at..];
            let open = rest.find('"').expect("a quoted command name after the call");
            let after = &rest[open + 1..];
            let close = after.find('"').expect("a closing quote");
            &after[..close]
        })
        .collect()
}

/// Every command name the Kotlin side answers to.
fn kotlin_command_names() -> Vec<&'static str> {
    KOTLIN
        .match_indices("@Command")
        .map(|(at, _)| {
            let rest = &KOTLIN[at..];
            let keyword = rest.find("fun ").expect("a fun after the annotation");
            let after = &rest[keyword + "fun ".len()..];
            let end = after.find('(').expect("a parameter list");
            after[..end].trim()
        })
        .collect()
}

#[test]
fn every_command_rust_calls_exists_on_the_kotlin_side() {
    let called = rust_command_names();
    let answered = kotlin_command_names();

    assert_eq!(
        called.len(),
        3,
        "expected exactly three calls into the plugin, found {called:?} — \
         a new one needs a Kotlin @Command and a line in this test"
    );

    for name in &called {
        assert!(
            answered.contains(name),
            "Rust calls `{name}` but the Kotlin class answers only {answered:?}. \
             On a device this is a runtime `No command {name} found`, discovered \
             by a user rather than by CI."
        );
    }
}

#[test]
fn the_kotlin_side_exposes_nothing_rust_does_not_call() {
    let called = rust_command_names();
    for name in kotlin_command_names() {
        assert!(
            called.contains(&name),
            "the Kotlin class exposes `{name}`, which nothing in Rust calls. \
             Dead command surface on the module that holds the root key."
        );
    }
}

#[test]
fn no_command_is_reachable_from_the_webview() {
    // build.rs registers no commands, so the ACL can grant nothing. If a name
    // ever appears in COMMANDS, a capability could allow it and any script in
    // the webview could read or destroy the sealed root record.
    let build = include_str!("../build.rs");
    assert!(
        build.contains("const COMMANDS: &[&str] = &[];"),
        "COMMANDS must stay empty: a listed command is autogenerated an \
         `allow-` permission and becomes callable from the webview over IPC."
    );
}

// ── the three states of `loadRecord` (CON-301's error model, TEST-304) ───────

#[test]
fn an_absent_record_is_not_an_error() {
    let response: LoadResponse = serde_json::from_str(r#"{"state":"absent"}"#).unwrap();
    assert_eq!(response, LoadResponse::Absent);
    assert_eq!(response.into_blob().unwrap(), None);
}

#[test]
fn a_present_record_yields_its_blob() {
    let response: LoadResponse =
        serde_json::from_str(r#"{"state":"present","blob":"{\"version\":1}"}"#).unwrap();
    assert_eq!(response.into_blob().unwrap(), Some("{\"version\":1}".to_string()));
}

/// The distinction the whole error model exists for: a damaged record MUST NOT
/// arrive as an absent one. A user told they have no identity will create a
/// second one over the top of the first.
#[test]
fn a_corrupt_record_is_an_error_and_never_an_absence() {
    let response: LoadResponse =
        serde_json::from_str(r#"{"state":"corrupt","detail":"tag mismatch"}"#).unwrap();
    match response.into_blob() {
        Err(StoreError::Corrupt(detail)) => assert_eq!(detail, "tag mismatch"),
        other => panic!("a corrupt record must not read as {other:?}"),
    }
}

/// An unknown state fails to parse rather than being treated as absent. If the
/// Kotlin side ever grows a fourth state, this is where it is noticed.
#[test]
fn an_unrecognised_state_is_refused() {
    assert!(serde_json::from_str::<LoadResponse>(r#"{"state":"maybe"}"#).is_err());
    assert!(serde_json::from_str::<LoadResponse>(r#"{}"#).is_err());
    // `present` without a blob is not a present record.
    assert!(serde_json::from_str::<LoadResponse>(r#"{"state":"present"}"#).is_err());
}

/// Each state literal Rust expects is the literal the Kotlin actually writes.
/// The two `serde` renames and the two field names are the whole vocabulary.
#[test]
fn the_state_literals_agree_across_the_two_languages() {
    for shape in [
        r#"state("absent")"#,
        r#"state("present")"#,
        r#"state("corrupt")"#,
        r#"put("blob", blob)"#,
        r#"put("detail", detail)"#,
    ] {
        assert!(
            KOTLIN.contains(shape),
            "the Kotlin side no longer writes `{shape}`, so `LoadResponse` \
             cannot deserialise what it sends"
        );
    }
}
